### ISSUE TITLE
Start using GitHub Projects for ClickHouse Roadmap

### ISSUE THREAD

**Issue by nvartolomei** [yandex/ClickHouse#4785]
Hi, I would like to have more visibility status and progress for projects mentioned in [roadmap for 2019](https://github.com/yandex/clickhouse-presentations/tree/master/roadmap2018).

1. See which features are still a priority and actively being worked on and how close to release these are.
2. See details on design decisions for these features and what are the steps to get there.

If more details would be open maybe people outside of Yandex would also start contributing towards these goals.

**Comment by blinkov** [comment]
High-level roadmap lives here and is updated several times a year: https://clickhouse.yandex/docs/en/roadmap/  

If you prefer that talk format, you can regularly visit our offline events (which is complicated since they are scattered all over the globe) or at least "Watch" that [repo with slides](https://github.com/yandex/clickhouse-presentations) on GitHub.

There's not much sense to use GitHub Projects at the moment since each of those features are usually implemented by a single person and even if there are few people involved, likely they are sitting in the same room.

**Comment by alexey-milovidov** [comment]
- [ ] LowCardinality: done
- [ ] Per column custom compression codecs: done
- [ ] Non-trivial default expressions for missing values in JSONEachRow format: done
- [ ] Parquet format: done
- [ ] HDFS: done
- [ ] S3: moved to Q2
- [ ] ALTER ORDER BY: done
- [ ] Compact metadata in ZooKeeper: done
- [ ] DDL for dictionaries: in progress, final stage
- [ ] Adaptive index granularity: in progress, final stage
- [ ] Row-level security: in progress, minimal variant is scheduled in Q1
- [ ] RBAC, LDAP: moved to spring
- [ ] Resource pools: moved to Q3
- [ ] Multiple JOINs: done
- [ ] Merge JOIN: moved to Q3
- [ ] Bucket-Shuffle JOIN: moved to Q4
- [ ] Secondary indices: done
- [ ] Simple machine learning as aggregate functions: in progress (early stage)
- [ ] ASOF JOIN: in progress (early stage)
- [ ] Optimization of ORDER BY and GROUP BY for primary key: in progress (early stage)
- [ ] Geohash: in progress (early stage)
- [ ] Polygon dictionaries: in progress (early stage, risky)
- [ ] Matching of multiple substrings: done
- [ ] Minhash/Simhash: in progress, scheduled for Q2
- [ ] Multiple storages for hot/cold data: in progress, scheduled for Q2
- [ ] JBOD and user-defined RAID: scheduled for Q2
- [ ] Embedded buffer for MergeTree: postponed

**Comment by alexey-milovidov** [comment]
> Polygon dictionaries

Cancelled (moved to 2020).

**Comment by denisgolius** [comment]
>     * RBAC, LDAP: moved to spring

Spring 2020 ?

**Comment by alexey-milovidov** [comment]
October 2019.

**Comment by alexey-milovidov** [comment]
November 2019.
